### ISSUE TITLE
The deployed module in ArgoCD is constantly out of sync

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-service-account#15]
ArgoCD tries to reconcile the imagePullSecret and pullSecret values that are automatically updated by kubernetes. This causes it to loop between in sync and out of sync.

The solution is to add an `ignoreDifferences` section in the ArgoCD application

**Comment by timroster** [comment]
@seansund should this get re-opened as the current gitops provider doesn't yet have code to pass along `ignoreDifferences` to the IGC module?

**Comment by timroster** [comment]
technically that's been rolled back, but I don't see in the current IGC gitops call an inclusion of local variable either.
