### ISSUE TITLE
The service account should support binding to an existing role

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-service-account#20]

**Comment by PriyaVasudevan** [comment]
@seansund  - We still see the issue open
The edit role should get applied on the service-account we create in the OMS module, rather than the pipeline account.
Here's the output for 'oc describe rolebinding.rbac -n gitops-cp-sterling-oms'
![image](https://user-images.githubusercontent.com/10666206/163326169-8926a4d9-a452-44f0-b24b-15aaad480b8f.png)

**Comment by yogendrasri** [comment]
module "service_account" {
  source = "github.com/cloud-native-toolkit/terraform-gitops-service-account.git"

  gitops_config = var.gitops_config
  git_credentials = var.git_credentials
  namespace = var.namespace
  name = local.sa_name
  sccs = ["anyuid", "privileged"]
  rbac_rules = [{
    apiGroups = [
      ""
    ]
    resources = [
      "secrets"      
    ]
    verbs = [
      "*"
    ]
    
  }]
  rbac_roles = [{
    name = "edit"
  
  }]
  rbac_cluster_scope = true
  server_name = var.server_name
  pull_secrets = ["ibm-entitlement-key"]
}

**Comment by yogendrasri** [comment]
@seansund Please let us know, if we are doing anything incorrect

**Comment by balasgit** [comment]
@PriyaVasudevan - am setting up call tomorrow understand more in detail about definition of Pipeline Account from your point of view ? Bcoz when i tried manual, only steps required for Service Account which is default that requires pull secret, entitlement-key,secrets etc

Once i understand the issue, we can socialize for options to resolve.

**Comment by balasgit** [comment]
<img width="748" alt="Screen Shot 2022-04-14 at 12 53 21 PM" src="https://user-images.githubusercontent.com/25986944/163448930-dfa30a51-dbce-4375-99ee-8f3084e61030.png">

**Comment by balasgit** [comment]
Reviewed the code as the team is trying to add the ibm-entitlement-key secret to ImagePullSecrets.. 

As per ServiceAccount, 

**variables definition** 

variable "rbac_roles" {
  type        = list(object({
    name      = string
  }))
  description = "List of existing roles or cluster roles for which a role binding should be created to this service account "
  default     = []
}

**Sample Values** 

  rbac_roles = [{
    name = "edit”
  }]

It didn't like the name field as part of rbac_roles as part of debugging..

**Comment by balasgit** [comment]
Tried with the "update" instead of edit which is one of the allowed RBAC roles.  Seems like it fixed the issues.. 

Next Step:
- Need to cleanup the namespaces from the cluster as well as argoCD on the fresh namespace 
- Need to deploy from Gitops and make sure everything works fine

**Comment by balasgit** [comment]
Verified using CLI for the Service account which is created and it has edit role based on the same command above running.

<img width="1463" alt="2022-04-14_17-25-32" src="https://user-images.githubusercontent.com/25986944/163487827-0764c217-a684-4093-8c44-cb2ce47e941a.png">
